# Generated by Django 3.1 on 2020-09-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='address1',
            new_name='adress1',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='address2',
            new_name='adress2',
        ),
    ]
